permalink: /:categories/:year-:i_month-:i_day-:title
highlighter: rouge

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: drewcutchins